# This file lists the dependencies needed to build and test all of the package.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: sage_binary-dev
channels:
  - conda-forge
dependencies:
  - black>=23,<24
  - docutils
  - furo
  - alabaster
  - isort
  - ipywidgets
  - jupyter-sphinx
  - jupytext
  - myst-parser
  - myst-nb
  - pip
  - pylint>=3,<3.1
  - rever
  - twine
  - wheel
  - arb
  - babel >=2.12.1,<3
  - bdw-gc >=8.0.4,<9
  - blas-devel
  - bleach >=5.0.1,<6
  - brial
  - cddlib >=1!0.94m
  - certifi
  - cliquer
  - cvxopt >=1.3.0,<2
  - cycler >=0.11.0
  - cypari2
  - cysignals
  - cython >=3,<4
  - decorator >=5.1.1,<6
  - docutils >=0.17.1
  - ecl >=21.2.1,<21.2.2.a0
  - eclib
  - ecm
  - entrypoints >=0.4
  - fflas-ffpack >=2.4.3
  - flintqs >=1.0,<2
  - fplll >=5.4.5,<6
  - fpylll >=0.6.0
  - freetype >=2.10.4,<3
  - gap-defaults >=4.12.2
  - gf2x >=1.3,<2
  - gfan >=0.6.2
  - giac >=1.9.0.15,<2
  - givaro >=4.1.1,<5
  - glpk
  - gmp
  - gmpy2
  - gsl
  - iml
  - ipykernel >=6.6.0,<7
  - ipython >=8.6.0,<9
  - ipywidgets >=8.0.2,<9
  - jinja2
  - jmol >=14.29.52,<15
  - jsonschema >=4.17.1,<5
  - jupyter_client >=7.4.4,<8
  - jupyter_core
  - lcalc
  - libbraiding
  - libflint
  - libgd
  - libhomfly
  - libiconv >=1.15,<2
  - libpng
  - linbox >=1.6.3
  - lrcalc >=2.1,<3
  - m4ri
  - m4rie
  - matplotlib-base >=3.8.0,<4
  - maxima >=5.46.0,<6
  - mistune >=2.0.4
  - mpc
  - mpfi
  - mpfr
  - mpmath >=1.3.0,<2
  - nauty >=2.8.6,<3
  - nbclient >=0.7.0,<0.8
  - nbconvert >=7.2.3,<8
  - nbformat >=5.7.0,<6
  - ncurses >=6.3,<7
  - networkx >=3.1,<4
  - notebook >=6.4.10,<7
  - ntl
  - numpy
  - palp >=2.11,<3
  - pari >=2.15.4,<3
  - pexpect >=4.8.0,<5
  - pkg-config
  - pkgconfig
  - pickleshare >=0.7.5,<1.0
  - pillow >=10.1.0,<11
  - planarity
  - ppl
  - pplpy 
  - primecountpy >=0.1.0,<0.2.0
  - ptyprocess >=0.7.0,<1
  - pygments >=2.13.0,<3
  - pyparsing >=3.1.1,<4
  - python >=3.9
  - python-dateutil >=2.8.2,<3
  - pythran >=0.14.0,<0.15
  - pytz >=2023.3.post1
  - pyzmq >=25.1.1,<26
  - readline
  - rpy2 >=3.4.5,<4
  - rubiks >=20070912
  - rw
  - sagelib
  - sagemath-db-combinatorial-designs >=20140630
  - sagemath-db-conway-polynomials >=0.5
  - sagemath-db-elliptic-curves >=0.8.1
  - sagemath-db-graphs >=20210214
  - sagemath-db-polytopes >=20170220
  - sagetex >=3.6.1,<4
  - scipy >=1.11.3,<2
  - simplegeneric >=0.8.1,<1
  - singular >=4.3.2p8,<4.4
  - six >=1.16.0,<2
  - sphinx >=5.2.3,<6
  - sqlite >=3.36,<4
  - symmetrica
  - sympow >=2.023.6,<3
  - sympy >=1.12,<2
  - tachyon 0.99.*
  - terminado >=0.17.0
  - three.js 122
  - tornado >=6.2,<7
  - traitlets >=5.9.0,<6
  - wcwidth >=0.2.5,<2
  - widgetsnbextension >=4.0.8,<5
  - zeromq >=4.3.5,<5
  - zlib
  - zn_poly

